logging:
  level:
    common: INFO
  file: logs/app.log
  pattern:
     console: "%d %-5level %logger : %msg%n"
     file: "%d %-5level [%thread] %logger : %msg%n"

spring.data.mongodb:
  database: applistener3
  uri: mongodb://localhost:27017


spring:
  mail:
      host: smtp.gmail.com
      port: 465
      username:
      password:
      properties.mail.smtp:
        auth: true
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory
          fallback: false

version.refresh.cron: 0 0/1 6-23,0 * * MON-SAT